version: 1
kind: discrete_maze
metadata:
  n_states: 40
  seed: 0
  width: 9
  height: 8
start_position:
- 7
- 5
goal_position:
- 8
- 0
goal_positions:
- - 8
  - 0
cells:
- - 0
  - 5
- - 0
  - 6
- - 1
  - 4
- - 1
  - 6
- - 1
  - 7
- - 2
  - 1
- - 2
  - 2
- - 2
  - 3
- - 2
  - 4
- - 2
  - 7
- - 3
  - 2
- - 3
  - 4
- - 3
  - 5
- - 3
  - 7
- - 4
  - 0
- - 4
  - 3
- - 4
  - 5
- - 4
  - 6
- - 4
  - 7
- - 5
  - 0
- - 5
  - 2
- - 5
  - 3
- - 5
  - 4
- - 5
  - 5
- - 5
  - 7
- - 6
  - 0
- - 6
  - 1
- - 6
  - 2
- - 6
  - 4
- - 6
  - 6
- - 6
  - 7
- - 7
  - 0
- - 7
  - 2
- - 7
  - 5
- - 7
  - 7
- - 8
  - 0
- - 8
  - 4
- - 8
  - 5
- - 8
  - 6
- - 8
  - 7
ascii: |-
  ####....G
  ##.###.##
  ##..#...#
  ##.#..###
  #...#..#.
  .##...#S.
  ..##.#.#.
  #........
