hydra:
  job:
    chdir: false
  run:
    dir: outputs/hydra/process_finetune_maze/${now:%Y-%m-%d_%H-%M-%S}

data:
  input_dir: data/raw/finetune_maze
  output_dir: data/processed/finetune_maze
  x_key: train/frame
  y_keys:
    - train/episode_reward

grid:
  n_points: 200
  min_x: null
  max_x: 50_000
  overlap_only: false
  extrapolate: false
