CUDA_DEVICE=${1:-0}

python train.py --config-name=train/finetune_maze agent=ddpg_discrete_with_kernel_actor agent.actor_lr=1e-7 p_path="/home/mprattico/distribution_matching/models/maze/108/pixels/rover/snapshot.pt" agent.feature_dim=200 agent.dataset_dim=4096 seed=0 env=gridworld/maze_108_seed7_env obs_type=pixels device=cuda:${CUDA_DEVICE}; 
python train.py --config-name=train/finetune_maze agent=ddpg_discrete_with_kernel_actor agent.actor_lr=1e-7 p_path="/home/mprattico/distribution_matching/models/maze/108/pixels/rover/snapshot.pt" agent.feature_dim=200 agent.dataset_dim=4096 seed=1 env=gridworld/maze_108_seed7_env obs_type=pixels device=cuda:${CUDA_DEVICE}; 
python train.py --config-name=train/finetune_maze agent=ddpg_discrete_with_kernel_actor agent.actor_lr=1e-7 p_path="/home/mprattico/distribution_matching/models/maze/108/pixels/rover/snapshot.pt" agent.feature_dim=200 agent.dataset_dim=4096 seed=2 env=gridworld/maze_108_seed7_env obs_type=pixels device=cuda:${CUDA_DEVICE}; 
python train.py --config-name=train/finetune_maze agent=ddpg_discrete_with_kernel_actor agent.actor_lr=1e-7 p_path="/home/mprattico/distribution_matching/models/maze/108/pixels/rover/snapshot.pt" agent.feature_dim=200 agent.dataset_dim=4096 seed=3 env=gridworld/maze_108_seed7_env obs_type=pixels device=cuda:${CUDA_DEVICE}; 
python train.py --config-name=train/finetune_maze agent=ddpg_discrete_with_kernel_actor agent.actor_lr=1e-7 p_path="/home/mprattico/distribution_matching/models/maze/108/pixels/rover/snapshot.pt" agent.feature_dim=200 agent.dataset_dim=4096 seed=4 env=gridworld/maze_108_seed7_env obs_type=pixels device=cuda:${CUDA_DEVICE}; 
python train.py --config-name=train/finetune_maze agent=ddpg_discrete_with_kernel_actor agent.actor_lr=1e-7 p_path="/home/mprattico/distribution_matching/models/maze/108/pixels/rover/snapshot.pt" agent.feature_dim=200 agent.dataset_dim=4096 seed=5 env=gridworld/maze_108_seed7_env obs_type=pixels device=cuda:${CUDA_DEVICE}; 
python train.py --config-name=train/finetune_maze agent=ddpg_discrete_with_kernel_actor agent.actor_lr=1e-7 p_path="/home/mprattico/distribution_matching/models/maze/108/pixels/rover/snapshot.pt" agent.feature_dim=200 agent.dataset_dim=4096 seed=6 env=gridworld/maze_108_seed7_env obs_type=pixels device=cuda:${CUDA_DEVICE}; 
