# @package _global_
defaults:
  - /agent: rover_nystrom_pointmaze
  - /env: pointmaze/pointmaze_largedense_goal_1
  - _self_

reward_free: true
domain: gym
task_name: ${env.name}
obs_type: states
frame_stack: 1
action_repeat: 1
discount: 0.99
resolution: 84
grayscale: false
random_init: true
random_goal: true
update_actor_after_critic_steps: 0

num_envs: 4
base_seed: ${seed}
async_vector_env: true

num_train_frames: 1_000_000
num_seed_frames: 10_000

eval_every_frames: 100_000
num_eval_episodes: 1
coverage_eval_enabled: true
coverage_num_trajectories: 50
coverage_grid_size: 90
coverage_radius: 0.08
coverage_expansion_tolerance: 0.25
plot_eval_trajectories: false

snapshots: [100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000]
snapshot_dir: models/pointmaze/largedense/states/rover_nystrom_parallel/${seed}

replay_buffer_size: 1000000
replay_buffer_num_workers: 1
batch_size: ${agent.batch_size}
nstep: ${agent.nstep}
update_encoder: true

agent:
  embeddings: false
  lr_actor: 100
  pmd_steps: 10
  update_every_steps: 100
  update_actor_every_steps: 10000
  pmd_eta_mode: backtracking
  pca_truncation: 4500
  compute_dtype: float64
  T_init_steps: 5000
  subsamples: 16000
  batch_size_actor: 16000
  lambda_reg: 1e-6
  kernel:
    subsampling_strategy: pivoted_cholesky
  sink_schedule: "linear(0.0,0.005,500000)"

seed: 1
device: cuda
save_video: false
save_train_video: false
save_buffer: false
save_snapshot: true
use_tb: true
use_wandb: false
save_log: true
wandb_project: pretrain_pointmaze_parallel
wandb_entity: urlb
wandb_tag: none
wandb_run_name: ${now:%Y.%m.%d}_${now:%H%M}_${task_name}_nenv${num_envs}
wandb_id: none
experiment: largedense_nystrom_online_parallel

hydra:
  run:
    dir: ./exp_local_parallel/${now:%Y.%m.%d}/${now:%H%M%S_%f}_${task_name}_nenv${num_envs}
  sweep:
    dir: ./exp_sweep_parallel/${now:%Y.%m.%d}/${now:%H%M}_${task_name}_${experiment}
    subdir: ${hydra.job.num}
