#!/usr/bin/env bash

CUDA_DEVICE=${1:-0}
python train.py --config-name=train/finetune agent=cic_discrete env=two_rooms7_0 device=cuda:${CUDA_DEVICE} wandb_tag=cic p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/cic/150034_212206_cic/models/discrete/gym/cic/1/snapshot.pt agent.actor_lr=1e-4 seed=0
python train.py --config-name=train/finetune agent=cic_discrete env=two_rooms7_0 device=cuda:${CUDA_DEVICE} wandb_tag=cic p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/cic/150034_212206_cic/models/discrete/gym/cic/1/snapshot.pt agent.actor_lr=1e-4 seed=1
python train.py --config-name=train/finetune agent=cic_discrete env=two_rooms7_0 device=cuda:${CUDA_DEVICE} wandb_tag=cic p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/cic/150034_212206_cic/models/discrete/gym/cic/1/snapshot.pt agent.actor_lr=1e-4 seed=2
python train.py --config-name=train/finetune agent=cic_discrete env=two_rooms7_0 device=cuda:${CUDA_DEVICE} wandb_tag=cic p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/cic/150034_212206_cic/models/discrete/gym/cic/1/snapshot.pt agent.actor_lr=1e-4 seed=3
python train.py --config-name=train/finetune agent=cic_discrete env=two_rooms7_0 device=cuda:${CUDA_DEVICE} wandb_tag=cic p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/cic/150034_212206_cic/models/discrete/gym/cic/1/snapshot.pt agent.actor_lr=1e-4 seed=4
python train.py --config-name=train/finetune agent=cic_discrete env=two_rooms7_0 device=cuda:${CUDA_DEVICE} wandb_tag=cic p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/cic/150034_212206_cic/models/discrete/gym/cic/1/snapshot.pt agent.actor_lr=1e-4 seed=5
python train.py --config-name=train/finetune agent=cic_discrete env=two_rooms7_0 device=cuda:${CUDA_DEVICE} wandb_tag=cic p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/cic/150034_212206_cic/models/discrete/gym/cic/1/snapshot.pt agent.actor_lr=1e-4 seed=6
