# @package _global_
# Pong Environment Configuration

env:
  name: "ALE/MontezumaRevenge-v5"
  render_mode: rgb_array
  atari:
    score_mask:
      enabled: true
  frameskip: 1
  repeat_action_probability: 0.0
  max_episode_steps: 18000
terminal_on_life_loss: true


# agent:
#   feature_dim: 512
