#!/usr/bin/env bash

CUDA_DEVICE=${1:-0}
python train.py --config-name=train/finetune agent=smm_discrete configs/env=multiplerooms5_4x4_1 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico-iit.local/distribution_matching/models/discrete/multiplerooms/smm/152103_182305_smm/models/discrete/gym/smm/1/snapshot.pt seed=0
python train.py --config-name=train/finetune agent=smm_discrete configs/env=multiplerooms5_4x4_1 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico-iit.local/distribution_matching/models/discrete/multiplerooms/smm/152103_182305_smm/models/discrete/gym/smm/1/snapshot.pt seed=1
python train.py --config-name=train/finetune agent=smm_discrete configs/env=multiplerooms5_4x4_1 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico-iit.local/distribution_matching/models/discrete/multiplerooms/smm/152103_182305_smm/models/discrete/gym/smm/1/snapshot.pt seed=2
python train.py --config-name=train/finetune agent=smm_discrete configs/env=multiplerooms5_4x4_1 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico-iit.local/distribution_matching/models/discrete/multiplerooms/smm/152103_182305_smm/models/discrete/gym/smm/1/snapshot.pt seed=3
python train.py --config-name=train/finetune agent=smm_discrete configs/env=multiplerooms5_4x4_1 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico-iit.local/distribution_matching/models/discrete/multiplerooms/smm/152103_182305_smm/models/discrete/gym/smm/1/snapshot.pt seed=4
python train.py --config-name=train/finetune agent=smm_discrete configs/env=multiplerooms5_4x4_1 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico-iit.local/distribution_matching/models/discrete/multiplerooms/smm/152103_182305_smm/models/discrete/gym/smm/1/snapshot.pt seed=5
python train.py --config-name=train/finetune agent=smm_discrete configs/env=multiplerooms5_4x4_1 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico-iit.local/distribution_matching/models/discrete/multiplerooms/smm/152103_182305_smm/models/discrete/gym/smm/1/snapshot.pt seed=6
