# @package _global_
defaults:
  - /env: multiplerooms5_4x4_0

task_name: ${env.name}
obs_type: states
frame_stack: 1
action_repeat: 1
resolution: 84
grayscale: false
random_init: false
random_goal: false
seed: 1

replay_buffer_dir: ???
coverage_intervals: [1000, 5000, 10000, 25000, 50000, 100000]
include_final_coverage: true

output_path: replay_buffer_coverage.csv

hydra:
  run:
    dir: .
