# @package _global_
defaults:
  - /env/gridworld: maze_108_seed7_env
  - _self_

task_name: ${env.name}
obs_type: pixels
frame_stack: 1
action_repeat: 1
resolution: 84
grayscale: false
random_init: false
random_goal: false
seed: 1

replay_buffer_dir: data_coverage/raw/maze/2026.05.05_states/024943_770762_dist_matching/buffer
output_path: heatmaps_replay_buffer/ROVER1
first_n_elements: 100_000
max_samples: null
pixel_nearest_batch_size: 64
heatmap_lower_percentile: 0
heatmap_upper_percentile: 99



hydra:
  run:
    dir: .
