# @package _global_

env:
  name: "PointMaze_UMaze-v3"
  render_mode: rgb_array
  max_episode_steps: 500
  pointmaze:
    top_down_camera: true
    discrete_actions: true
    direct_velocity_actions: true
    max_velocity: 5.0
    only_xy_position: true
    start_position: [1.0, 0.0]
    start_position_variance: 0.0
    reward_type: sparse    
    goal_position: [-1.0, -1.0]
