# @package agent
_target_: agent.dist_matching.DistMatchingAgent
name: dist_matching
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
lr_actor: 0.05 # eta
discount: ${discount} # gamma
alpha: 0.0
learn_T: true # whether to learn the T operator
lr_T: 1e-4
batch_size: 1024
nstep: 1
update_every_steps: 1
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
starting_policy: uniform # [uniform, random]
device: ${device}
linear_actor: false
