# @package agent
_target_: agent.dist_matching_embedding_augmented_v2.DistMatchingEmbeddingAgentv2
name: dist_matching
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
lr_actor: 10 # eta
discount: ${discount} # gamma
lambda_reg: 1e-8
lr_T: 1e-3
batch_size: 1024
batch_size_actor: 5000
nstep: 1
lr_encoder: 1e-3
curl: true
embedding_sum_loss: 0.1
hidden_dim: 1024
feature_dim: null
T_init_steps: 1000
update_every_steps: 1
update_actor_every_steps: 1500
pmd_steps: 100
sink_schedule: linear(0.0,0.04,50000)
epsilon_schedule: 0.15
embeddings: true  # whether to use embeddings or not, if obs_type is pixels this is always true
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
device: ${device}