# @package agent
_target_: agent.dist_matching_embedding_continuous.DistMatchingEmbeddingAgent
name: dist_matching
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
lr_actor: 0.05 # eta
discount: ${discount} # gamma
lambda_reg: 1e-10
lr_T: 1e-5
batch_size: 1024
nstep: 1
lr_encoder: 1e-5
hidden_dim: 512
feature_dim: 256
T_init_steps: 300
update_every_steps: 1
update_actor_every_steps: 960
n_subsamples: null
pmd_steps: 15000
data_type: unique # [unique, all]
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
device: ${device}
linear_actor: false
ideal: false
