# @package agent
_target_: agent.rnd_discrete.RNDAgent
name: rnd
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
rnd_lr: 1e-4
actor_lr: 1e-4
critic_lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
rnd_rep_dim: 512
eps_schedule: 0.25
rnd_scale: 1.0
nstep: 1
batch_size: 1024
init_critic: true
linear_actor: false
update_encoder: ${update_encoder}
update_actor_after_critic_steps: ${update_actor_after_critic_steps}

