  # @package agent

_target_: agent.sac_discrete_with_kernel_actor.SACAgent
name: discrete_sac
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
update_actor_after_critic_steps: ${update_actor_after_critic_steps}
hidden_dim: 1024
dataset_dim: 556
eta: 0.5
feature_dim: 50
batch_size: 1024 # 256 for pixels
init_temperature: 0.1
update_every_steps: 2
eps_schedule: 0.25
nstep: 1
alpha_lr: 1e-5
actor_lr: 1e-5
actor_update_frequency: 1
critic_lr: 1e-5
critic_target_tau: 0.01
critic_target_update_frequency: 1
init_critic: false  
learnable_temperature: true
  
