#!/usr/bin/env bash

CUDA_DEVICE=${1:-0}
python train.py --config-name=train/finetune agent=smm_discrete env=two_rooms7_2 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/smm/152055_951603_smm/models/discrete/gym/smm/1/snapshot.pt agent.actor_lr=1e-7 seed=0
python train.py --config-name=train/finetune agent=smm_discrete env=two_rooms7_2 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/smm/152055_951603_smm/models/discrete/gym/smm/1/snapshot.pt agent.actor_lr=1e-7 seed=1
python train.py --config-name=train/finetune agent=smm_discrete env=two_rooms7_2 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/smm/152055_951603_smm/models/discrete/gym/smm/1/snapshot.pt agent.actor_lr=1e-7 seed=2
python train.py --config-name=train/finetune agent=smm_discrete env=two_rooms7_2 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/smm/152055_951603_smm/models/discrete/gym/smm/1/snapshot.pt agent.actor_lr=1e-7 seed=3
python train.py --config-name=train/finetune agent=smm_discrete env=two_rooms7_2 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/smm/152055_951603_smm/models/discrete/gym/smm/1/snapshot.pt agent.actor_lr=1e-7 seed=4
python train.py --config-name=train/finetune agent=smm_discrete env=two_rooms7_2 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/smm/152055_951603_smm/models/discrete/gym/smm/1/snapshot.pt agent.actor_lr=1e-7 seed=5
python train.py --config-name=train/finetune agent=smm_discrete env=two_rooms7_2 device=cuda:${CUDA_DEVICE} wandb_tag=smm p_path=/home/mprattico/distribution_matching/models/discrete/two_rooms/smm/152055_951603_smm/models/discrete/gym/smm/1/snapshot.pt agent.actor_lr=1e-7 seed=6
